/* Generated by solo5-mfttool, do not edit */

#define MFT_ENTRIES 2
#include "mft_abi.h"

MFT1_NOTE_DECLARE_BEGIN
{
  .version = MFT_VERSION, .entries = 2,
  .e = {
    { .name = "", .type = MFT_RESERVED_FIRST },
    { .name = "storage", .type = MFT_DEV_BLOCK_BASIC },
  }
}
MFT1_NOTE_DECLARE_END
