/* Generated by solo5-mfttool, do not edit */

#define MFT_ENTRIES 3
#include "mft_abi.h"

MFT1_NOTE_DECLARE_BEGIN
{
  .version = MFT_VERSION, .entries = 3,
  .e = {
    { .name = "", .type = MFT_RESERVED_FIRST },
    { .name = "service0", .type = MFT_DEV_NET_BASIC },
    { .name = "service1", .type = MFT_DEV_NET_BASIC },
  }
}
MFT1_NOTE_DECLARE_END
